### ISSUE TITLE
Remove progress bar from html5 video player in full screen

### ISSUE THREAD

**Issue by naif-sameer** [naif-sameer/my-issues#3]
```css
audio::-webkit-media-controls-timeline,
video::-webkit-media-controls-timeline {
    display: none;
}
audio::-webkit-media-controls,
video::-webkit-media-controls {
    display: none;
}

```

[stackoverflow](https://stackoverflow.com/a/31743661/19299063)
